global:
  scrape_interval: 5s
  evaluation_interval: 5s

scrape_configs:
  - job_name: "ingestion"
    static_configs:
      - targets: ["ingestion:8001"]

  - job_name: "feature"
    static_configs:
      - targets: ["feature:8002"]

  - job_name: "scoring"
    static_configs:
      - targets: ["scoring:8003"]

  - job_name: "alert"
    static_configs:
      - targets: ["alert:8004"]

  - job_name: "gateway"
    static_configs:
      - targets: ["gateway:8000"]
